### ISSUE TITLE
Restrict Project Status Changes

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-docs#19]
This issue focuses on implementing a CI/CD process to verify that only authorized team leads can change the project status. By restricting access to project status changes, we can maintain control over the project's progression and prevent unauthorized modifications that may disrupt workflow or cause confusion.

**Comment by ebrarkesici** [comment]
https://github.com/octoposprime/op-be-docs.git
Here I wrote a yaml file called "restrict_project_status_changes.yml".

**Comment by Sddilora** [comment]
can you test this workflow on https://github.com/Ubn-Jr/octoposPrimeDev then open pr if it is working

**Comment by Sddilora** [comment]
This operation will not be performed by team leads in the future, so this action is no longer needed.
