### ISSUE TITLE
Implement Pull Request Labeling Process

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-docs#21]
This issue involves implementing a CI/CD process to apply appropriate labels to pull requests based on their content, changes, or other relevant factors. Proper labeling of pull requests helps categorize and prioritize them, facilitating efficient code review and merging workflows.

**Comment by mervegonc** [comment]
I didn't understand what should i do about this issue.

**Comment by Sddilora** [comment]
Our team has a workflow where issues are labeled, but our pull requests aren't getting labeled. Could you write a workflow for that? You can take an example from the link in this [create-issue.yaml workflow.](https://github.com/octoposprime/op-be-docs/blob/phase1/.github/workflows/create-issue.yaml)
