### ISSUE TITLE
Docker Image Pull Authorization Issue

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-docs#4]
-**Operating System:** Windows 11
- **Docker Version:** 24.0.6
- **Command Used:**docker run --pull=always -d --expose 18080 -p 18080:18080 --network op -e TEST=true --name op-be-graphql ghcr.io/octoposprime/op-be-graphql:latest
- **Error Message:**docker: Error response from daemon: Head "https://ghcr.io/v2/octoposprime/op-be-graphql/manifests/latest": denied. See 'docker run --help'.

1. Docker was started on Windows.
2. Executed the command mentioned above.
3. Encountered the error message.

**Comment by husamettinarabaci** [comment]
There aren't any released containers yet. It will be there after the release of v0.0.1. You have to run locally until publishing the first release.
