### ISSUE TITLE
Makefile Fixing for Docker

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-docs#7]
We have to change params and commands in the Dockerfile that should be suitable to .env.

Projects;
- logging
- user
- graphql

We have to add this ;

```
POSTGRES_USERNAME?=op#Postgres Db User Name
POSTGRES_PASSWORD?=op#Postgres Db Password
JWT_SECRET_KEY?=op#Jwt Secret Key
REDIS_PASSWORD?=vstguard#Redis Password
```

and we have to change;

```
## Docker:
docker-build: ## Use the Dockerfile to build the container
	docker build --rm --tag $(DOCKER_REPOSITORY)/$(DOCKER_CONTAINER) \
	--build-arg TEST=$(TEST) \
	--build-arg POSTGRES_USERNAME=$(POSTGRES_USERNAME) \
	--build-arg POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
	--build-arg JWT_SECRET_KEY=$(JWT_SECRET_KEY) \
	--build-arg REDIS_PASSWORD=$(REDIS_PASSWORD) .
```

**Comment by Sddilora** [comment]
REDIS_PASSWORD=vstguard#Redis Password I changed this part to "op" when creating the issues.

**Comment by Sddilora** [comment]
> We have to change params and commands in the Dockerfile that should be suitable to .env.
> 
> Projects;
> 
> * logging
> * user
> * graphql
> 
> We have to add this ;
> 
> ```
> POSTGRES_USERNAME?=op#Postgres Db User Name
> POSTGRES_PASSWORD?=op#Postgres Db Password
> JWT_SECRET_KEY?=op#Jwt Secret Key
> REDIS_PASSWORD?=vstguard#Redis Password
> ```
> 
> and we have to change;
> 
> ```
> ## Docker:
> docker-build: ## Use the Dockerfile to build the container
> 	docker build --rm --tag $(DOCKER_REPOSITORY)/$(DOCKER_CONTAINER) \
> 	--build-arg TEST=$(TEST) \
> 	--build-arg POSTGRES_USERNAME=$(POSTGRES_USERNAME) \
> 	--build-arg POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
> 	--build-arg JWT_SECRET_KEY=$(JWT_SECRET_KEY) \
> 	--build-arg REDIS_PASSWORD=$(REDIS_PASSWORD) .
> ```

the file needs to be changed is Makefile right

**Comment by husamettinarabaci** [comment]
> REDIS_PASSWORD=vstguard#Redis Password I changed this part to "op" when creating the issues.

It should be REDIS_PASSWORD?=XXXX.
The "?" operator is important in there.

**Comment by husamettinarabaci** [comment]
> > We have to change params and commands in the Dockerfile that should be suitable to .env.
> > Projects;
> > 
> > * logging
> > * user
> > * graphql
> > 
> > We have to add this ;
> > ```
> > POSTGRES_USERNAME?=op#Postgres Db User Name
> > POSTGRES_PASSWORD?=op#Postgres Db Password
> > JWT_SECRET_KEY?=op#Jwt Secret Key
> > REDIS_PASSWORD?=vstguard#Redis Password
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and we have to change;
> > ```
> > ## Docker:
> > docker-build: ## Use the Dockerfile to build the container
> > 	docker build --rm --tag $(DOCKER_REPOSITORY)/$(DOCKER_CONTAINER) \
> > 	--build-arg TEST=$(TEST) \
> > 	--build-arg POSTGRES_USERNAME=$(POSTGRES_USERNAME) \
> > 	--build-arg POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
> > 	--build-arg JWT_SECRET_KEY=$(JWT_SECRET_KEY) \
> > 	--build-arg REDIS_PASSWORD=$(REDIS_PASSWORD) .
> > ```
> 
> the file needs to be changed is Makefile right

Yes. It should have been Makefile.

**Comment by Sddilora** [comment]
Issues created for desired repos

- [X] User
    https://github.com/octoposprime/op-be-user/issues/17
- [x] Graphql
    https://github.com/octoposprime/op-be-graphql/issues/9
- [x] Logging
    https://github.com/octoposprime/op-be-logging/issues/5

**Comment by Sddilora** [comment]
files fixed
